config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'
  resources :orders
  resources :customers
  resources :batches
  resources :farmers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/' => 'pages#home'

  root to: 'landing#index'

end

app/models/farmer.rb
class Farmer < ApplicationRecord
  has_many :batches
end

app/controllers/farmers_controller.rb
class FarmersController < ApplicationController
  before_action :set_farmer, only: [:show, :edit, :update, :destroy]

  # GET /farmers
  # GET /farmers.json
  def index
    @farmers = Farmer.all
  end

  # GET /farmers/1
  # GET /farmers/1.json
  def show
    @farmer = Farmer.find_by_id(params[:id])
    @zip = ZipCodes.identify(@farmer.location.to_s)
    @batches = @farmer.batches
    @customer = Customer.first
  end

  # GET /farmers/new
  def new
    @farmer = Farmer.new
  end

  # GET /farmers/1/edit
  def edit
  end

  # POST /farmers
  # POST /farmers.json
  def create
    @farmer = Farmer.new(farmer_params)

    respond_to do |format|
      if @farmer.save
        format.html { redirect_to @farmer, notice: 'Farmer was successfully created.' }
        format.json { render :show, status: :created, location: @farmer }
      else
        format.html { render :new }
        format.json { render json: @farmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farmers/1
  # PATCH/PUT /farmers/1.json
  def update
    respond_to do |format|
      if @farmer.update(farmer_params)
        format.html { redirect_to @farmer, notice: 'Farmer was successfully updated.' }
        format.json { render :show, status: :ok, location: @farmer }
      else
        format.html { render :edit }
        format.json { render json: @farmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farmers/1
  # DELETE /farmers/1.json
  def destroy
    @farmer.destroy
    respond_to do |format|
      format.html { redirect_to farmers_url, notice: 'Farmer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farmer
      @farmer = Farmer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def farmer_params
      params.require(:farmer).permit(:email, :name, :location)
    end
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/views/farmers/_form.html.erb
<%= form_with(model: farmer, local: true) do |form| %>
  <% if farmer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(farmer.errors.count, "error") %> prohibited this farmer from being saved:</h2>

      <ul>
      <% farmer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.number_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/farmers/edit.html.erb
<h1>Editing Farmer</h1>

<%= render 'form', farmer: @farmer %>

<%= link_to 'Show', @farmer %> |
<%= link_to 'Back', farmers_path %>

app/views/farmers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Farmers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @farmers.each do |farmer| %>
      <tr>
        <td><%= farmer.email %></td>
        <td><%= farmer.name %></td>
        <td><%= farmer.location %></td>
        <td><%= link_to 'Show', farmer %></td>
        <td><%= link_to 'Edit', edit_farmer_path(farmer) %></td>
        <td><%= link_to 'Destroy', farmer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Farmer', new_farmer_path %>

app/views/farmers/new.html.erb
<h1>New Farmer</h1>

<%= render 'form', farmer: @farmer %>

<%= link_to 'Back', farmers_path %>

app/views/farmers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @farmer.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @farmer.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @zip %>
</p>

<br><br>
  <div>
    <h4>OPEN BATCHES</h4>
    <%@batches.each do |batch| %>
    <ul>
      <li>Name:<%=batch.name%></li>
      <li>Description:<%=batch.desc%></li>
      <li>Amount:<%=batch.amount%> kilos</li>
      <li>Price per kilo:$<%=batch.price%></li>
    </ul>
    <%= link_to "Buy #{batch.name}", new_order_url(:batch => batch.id, :customer => @customer.id)%><h4>
    <br>

    <%end%>
  </div>

  <div>
  </div>