config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'
  resources :orders
  resources :customers
  resources :batches
  resources :farmers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/' => 'pages#home'

  root to: 'landing#index'

end

app/models/batch.rb
class Batch < ApplicationRecord
  belongs_to :farmer
  has_many :orders
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :set_batch, only: [:show, :edit, :update, :destroy]

  # GET /batches
  # GET /batches.json
  def index
    @batches = Batch.all
  end

  # GET /batches/1
  # GET /batches/1.json
  def show
  end

  # GET /batches/new
  def new
    @batch = Batch.new
  end

  # GET /batches/1/edit
  def edit
  end

  # POST /batches
  # POST /batches.json
  def create
    @batch = Batch.new(batch_params)

    respond_to do |format|
      if @batch.save
        format.html { redirect_to @batch, notice: 'Batch was successfully created.' }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render :new }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /batches/1
  # PATCH/PUT /batches/1.json
  def update
    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to @batch, notice: 'Batch was successfully updated.' }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render :edit }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1
  # DELETE /batches/1.json
  def destroy
    @batch.destroy
    respond_to do |format|
      format.html { redirect_to batches_url, notice: 'Batch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_batch
      @batch = Batch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def batch_params
      params.require(:batch).permit(:name, :desc, :amount, :price, :farmer_id)
    end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_form.html.erb
<%= form_with(model: batch, local: true) do |form| %>
  <% if batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
      <% batch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :farmer_id %>
    <%= form.text_field :farmer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/batches/edit.html.erb
<h1>Editing Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Show', @batch %> |
<%= link_to 'Back', batches_path %>

app/views/batches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Batches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Amount</th>
      <th>Price</th>
      <th>Farmer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= batch.name %></td>
        <td><%= batch.desc %></td>
        <td><%= batch.amount %></td>
        <td><%= batch.price %></td>
        <td><%= batch.farmer %></td>
        <td><%= link_to 'Show', batch %></td>
        <td><%= link_to 'Edit', edit_batch_path(batch) %></td>
        <td><%= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Batch', new_batch_path %>

app/views/batches/new.html.erb
<h1>New Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Back', batches_path %>

app/views/batches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @batch.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @batch.desc %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @batch.amount %>
</p>

<p>
  <strong>Price:</strong>
  <%= @batch.price %>
</p>

<p>
  <strong>Farmer:</strong>
  <%= @batch.farmer %>
</p>

<%= link_to 'Edit', edit_batch_path(@batch) %> |
<%= link_to 'Back', batches_path %>